CREATE TABLE users (
   id BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
   name VARCHAR(50) NOT NULL,
   email VARCHAR(50) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL,
   role VARCHAR(150) NOT NULL
);